# Generated by Django 5.0.4 on 2024-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('CustomerName', models.TextField()),
                ('Password', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=12)),
                ('Address', models.TextField()),
            ],
        ),
    ]
