# Generated by Django 5.0.4 on 2024-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniformUniverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('UniformID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('UniformName', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Stock', models.IntegerField()),
            ],
        ),
    ]
